
;; ================================================================
;; 
;; ATTENTION: DO NOT EDIT THIS FILE DIRECTLY. 
;;
;;            Edit ../../org/iwtf.org instead. The content of this 
;;            source code file is generated from iwtf.org.
;;
;; ================================================================









;; The only reason to look at this generated code directly is if
;; you're curious about the output of the org literate workflow.



































;; You have been warned.
(ns iwtf.web-test
  (:use iwtf.web-common))
(defn fixture-new-browser
  "clojure.test fixture creates a new *browser*. if the fixture is
  used with :each, there will be a new browser for each test in the
  namespace. with :once, all tests in a single namespace will share
  the same browser. note: some namespaces can use :each while others
  use :once. if you use :once, you should also use
  fixture-delete-all-cookies as :each."
  [f]
  (binding [*browser* (new-firefox-browser)]
    (f)
    (end)))
(defn fixture-delete-all-cookies
  "clojure.test fixture deletes all cookies from *browser* even if an
  exception occurs during the test(s)"
  [f]
  (f)
  (delete-all-cookies))
